framework:
    translator: { fallbacks: ["%locale%"] }
    secret: '%env(APP_SECRET)%'
    form: true
    csrf_protection: true
    session:
        handler_id: ~

    router:
        default_uri: '%env(BASE_URI)%'