google_tag_manager:
    enabled: true
    id: '%env(resolve:GOOGLE_TAG_MANAGER_ID)%'
    autoAppend: false

gtm:
    inject: true
    features:
        environment: true
        route: true
        context: true
        events: true