google_tag_manager:
    enabled: true
    id: "GTM-PDG7C32"
    autoAppend: false

gtm:
    inject: true
    features:
        environment: true
        route: true
        context: true
        events: true