liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        chullanka_nav_element:
            quality: 75
            filters:
                thumbnail: { size: [600, 90], mode: inset }
        chullanka_category:
            quality: 75
            filters:
                thumbnail: { size: [1600, 900], mode: inset }
