sylius_mailer:
    sender:
        name: '%env(resolve:MAILER_SENDER_NAME)%'
        address: '%env(resolve:MAILER_SENDER_EMAIL)%'
    emails:
        ask_recall:
            subject: "Demande de rappel"
            template: "emails/ask_recall.html.twig"
        ask_return_product:
            subject: "Nouvelle demande de retour produit"
            template: "emails/ask_return_product.html.twig"
        rma_return_accepted:
            subject: "Retour produit accepté, à vous de jouer !"
            template: "emails/rma_return_accepted.html.twig"
        rma_return_refused:
            subject: "Votre demande de retour a été réfusée"
            template: "emails/rma_return_refused.html.twig"
        rma_change_state:
            subject: "Votre demande de retour produit"
            template: "emails/rma_change_state.html.twig"
        click_and_collect:
            subject: "Nouvelle commande Click&Collect"
            template: "emails/click_and_collect.html.twig"